# Generated by Django 5.2.9 on 2025-12-05 14:52

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('landlord', '房東'), ('tenant', '租客'), ('admin', '管理員')], default='tenant', max_length=20, verbose_name='角色')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='電話')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='頭像')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='註冊時間')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用戶',
                'verbose_name_plural': '用戶',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='房源標題')),
                ('description', models.TextField(verbose_name='房源描述')),
                ('property_type', models.CharField(choices=[('entire', '整套房'), ('private', '獨立房間'), ('shared', '共享房間')], default='entire', max_length=20, verbose_name='房源類型')),
                ('city', models.CharField(max_length=100, verbose_name='城市')),
                ('district', models.CharField(max_length=100, verbose_name='區域')),
                ('address', models.CharField(max_length=255, verbose_name='地址')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='緯度')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='經度')),
                ('bedrooms', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='臥室數')),
                ('bathrooms', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='浴室數')),
                ('max_guests', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='最大入住人數')),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='每晚價格')),
                ('is_available', models.BooleanField(default=True, verbose_name='是否可用')),
                ('amenities', models.JSONField(blank=True, default=list, verbose_name='設施')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL, verbose_name='房東')),
            ],
            options={
                'verbose_name': '房源',
                'verbose_name_plural': '房源',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField(verbose_name='入住日期')),
                ('check_out', models.DateField(verbose_name='退房日期')),
                ('guests', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='入住人數')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='總價格')),
                ('status', models.CharField(choices=[('pending', '待確認'), ('confirmed', '已確認'), ('cancelled', '已取消'), ('completed', '已完成')], default='pending', max_length=20, verbose_name='預訂狀態')),
                ('booking_number', models.CharField(editable=False, max_length=50, unique=True, verbose_name='預訂編號')),
                ('notes', models.TextField(blank=True, verbose_name='備註')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='租客')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='properties.property', verbose_name='房源')),
            ],
            options={
                'verbose_name': '預訂',
                'verbose_name_plural': '預訂',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties/', verbose_name='圖片')),
                ('is_cover', models.BooleanField(default=False, verbose_name='是否為封面圖')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上傳時間')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property', verbose_name='房源')),
            ],
            options={
                'verbose_name': '房源圖片',
                'verbose_name_plural': '房源圖片',
                'ordering': ['order', '-uploaded_at'],
            },
        ),
    ]
