# Generated by Django 5.2.8 on 2025-12-06 08:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RentalRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="需求標題")),
                ("description", models.TextField(verbose_name="需求描述")),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("entire", "整套房"),
                            ("private", "獨立房間"),
                            ("shared", "共享房間"),
                        ],
                        max_length=20,
                        verbose_name="房源類型",
                    ),
                ),
                (
                    "preferred_city",
                    models.CharField(max_length=100, verbose_name="偏好城市"),
                ),
                (
                    "preferred_district",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="偏好區域"
                    ),
                ),
                (
                    "min_bedrooms",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="最少臥室數",
                    ),
                ),
                (
                    "min_bathrooms",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="最少浴室數",
                    ),
                ),
                (
                    "max_guests",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="入住人數",
                    ),
                ),
                (
                    "budget_range",
                    models.CharField(
                        choices=[
                            ("0-1000", "NT$0 - NT$1,000"),
                            ("1000-2000", "NT$1,000 - NT$2,000"),
                            ("2000-3000", "NT$2,000 - NT$3,000"),
                            ("3000-5000", "NT$3,000 - NT$5,000"),
                            ("5000+", "NT$5,000+"),
                        ],
                        max_length=20,
                        verbose_name="預算範圍",
                    ),
                ),
                (
                    "move_in_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="期望入住日期"
                    ),
                ),
                (
                    "rental_duration",
                    models.IntegerField(
                        blank=True,
                        help_text="預計租住天數",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="租期（天）",
                    ),
                ),
                (
                    "desired_amenities",
                    models.JSONField(blank=True, default=list, verbose_name="期望設施"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否有效"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="創建時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rental_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="租客",
                    ),
                ),
            ],
            options={
                "verbose_name": "租客需求",
                "verbose_name_plural": "租客需求",
                "ordering": ["-created_at"],
            },
        ),
    ]
